ACC=
CC=$(ACC) gcc
REMCFLAGS     = -Wall -Wshadow -I.. -DLIST_STATS -DLIST_HISTOGRAM $(SIMGRAPH)

DEST	      = .

HDRS	      = inputAction.h \
		inputActionTable.h \
		utils.h

INSTALL	      = /etc/install

LD	      = ld

LDFLAGS	      = 

LIBS	      =

MAKEFILE      = Makefile

OBJS	      = ${SRCS:.c=.o} 

PRINT	      = pr

PROGRAM       = inputActions.o

SHELL	      = /bin/sh

SRCS	      = defaultInputAction.c \
							utils.c

SYSHDRS	      =

all:	
		$(MAKE) optall

optall: 
		$(MAKE) $(PROGRAM) CFLAGS="-O3 $(REMCFLAGS)"

debugall:
		$(MAKE) $(PROGRAM) CFLAGS="-g $(REMCFLAGS)"

$(PROGRAM)::     $(OBJS) $(LIBS)
		@echo "Linking clean sim: $(PROGRAM) ..."
		$(LD) -r $(OBJS) $(LDFLAGS) $(LIBS) -o $(PROGRAM)
		@echo "done"

clean:;		rm -f $(OBJS) $(PROGRAM) core

clobber:;	rm -f $(OBJS) $(PROGRAM) core tags

##depend:;	@mkmf -f $(MAKEFILE) ROOT=$(ROOT)

depend:;	makedepend -o.o -- $(REMCFLAGS) -- $(SRCS)


echo:;		@echo $(HDRS) $(SRCS)

index:;		ctags -wx $(HDRS) $(SRCS)

install::	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
#		@-strip $(PROGRAM)
		if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi

print:;		$(PRINT) $(HDRS) $(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

###
# DO NOT DELETE THIS LINE -- make depend depends on it.

defaultInputAction.o: ../sim.h /usr/include/stdio.h /usr/include/features.h
defaultInputAction.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
defaultInputAction.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
defaultInputAction.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
defaultInputAction.o: /usr/include/libio.h /usr/include/_G_config.h
defaultInputAction.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
defaultInputAction.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
defaultInputAction.o: /usr/include/sys/types.h /usr/include/time.h
defaultInputAction.o: /usr/include/endian.h /usr/include/bits/endian.h
defaultInputAction.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
defaultInputAction.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
defaultInputAction.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
defaultInputAction.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
defaultInputAction.o: /usr/include/math.h /usr/include/bits/huge_val.h
defaultInputAction.o: /usr/include/bits/huge_valf.h
defaultInputAction.o: /usr/include/bits/huge_vall.h /usr/include/bits/inf.h
defaultInputAction.o: /usr/include/bits/nan.h /usr/include/bits/mathdef.h
defaultInputAction.o: /usr/include/bits/mathcalls.h ../bitmap.h ../stat.h
defaultInputAction.o: ../histogram.h ../lists.h ../switchStats.h ../types.h
defaultInputAction.o: ../latencyStats.h ../functionTable.h inputAction.h
utils.o: /usr/include/sys/types.h /usr/include/features.h
utils.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
utils.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
utils.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
utils.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
utils.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
utils.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
utils.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
utils.o: /usr/include/bits/pthreadtypes.h /usr/include/sys/time.h
