ACC=
CC=$(ACC) gcc
REMCFLAGS     = -Wall -Wshadow \
			 -I.. -I../INPUTACTIONS\
		         -DLIST_STATS -DLIST_HISTOGRAM $(SIMGRAPH)

DEST	      = .

HDRS	      = fabric.h\
				fabricTable.h\
				inputAction.h

INSTALL	      = /etc/install

LD	          = ld

LDFLAGS	      =

LIBS	      =

OBJS	      = ${SRCS:.c=.o}

PRINT	      = pr

PROGRAM       = fabrics.o

SHELL	      = /bin/sh

SRCS	      = crossbar.c \
                output.c

SYSHDRS	      =
all:	
		$(MAKE) optall

optall: 
		$(MAKE) $(PROGRAM) CFLAGS="-O3 $(REMCFLAGS)"

debugall:
		$(MAKE) $(PROGRAM) CFLAGS="-g $(REMCFLAGS)"

$(PROGRAM)::     $(OBJS) $(LIBS)
		@echo "Linking clean sim: $(PROGRAM) ..."
		$(LD) -r $(OBJS) $(LDFLAGS) $(LIBS) -o $(PROGRAM)
		@echo "done"

clean:;		rm -f $(OBJS) $(PROGRAM) core

clobber:;	rm -f $(OBJS) $(PROGRAM) core tags

depend:;	makedepend -o.o -- $(REMCFLAGS) -- $(SRCS)

echo:;		@echo $(HDRS) $(SRCS)

index:;		ctags -wx $(HDRS) $(SRCS)

install::	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
#		@-strip $(PROGRAM)
		if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi

print:;		@$(PRINT) $(HDRS) $(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

###
# DO NOT DELETE THIS LINE -- make depend depends on it.

crossbar.o: ../sim.h /usr/include/stdio.h /usr/include/features.h
crossbar.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
crossbar.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
crossbar.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
crossbar.o: /usr/include/libio.h /usr/include/_G_config.h
crossbar.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
crossbar.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
crossbar.o: /usr/include/sys/types.h /usr/include/time.h
crossbar.o: /usr/include/endian.h /usr/include/bits/endian.h
crossbar.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
crossbar.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
crossbar.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
crossbar.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
crossbar.o: /usr/include/math.h /usr/include/bits/huge_val.h
crossbar.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
crossbar.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
crossbar.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
crossbar.o: ../bitmap.h ../stat.h ../histogram.h ../lists.h ../switchStats.h
crossbar.o: ../types.h ../latencyStats.h ../functionTable.h fabric.h
crossbar.o: ../INPUTACTIONS/inputAction.h /usr/include/string.h
crossbar.o: /usr/include/xlocale.h
output.o: ../sim.h /usr/include/stdio.h /usr/include/features.h
output.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
output.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
output.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
output.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
output.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
output.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
output.o: /usr/include/endian.h /usr/include/bits/endian.h
output.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
output.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
output.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
output.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
output.o: /usr/include/math.h /usr/include/bits/huge_val.h
output.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
output.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
output.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
output.o: ../bitmap.h ../stat.h ../histogram.h ../lists.h ../switchStats.h
output.o: ../types.h ../latencyStats.h ../functionTable.h fabric.h
output.o: ../INPUTACTIONS/inputAction.h /usr/include/string.h
output.o: /usr/include/xlocale.h
